issuetracker/urls.py
import logging
import os

from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from issuetracker.settings import BASE_DIR

logger = logging.getLogger(__name__)

logger.info("System is starting with [env=%s, db=%s]", settings.ENV, settings.DATABASES["default"]["ENGINE"])

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("tasks.urls")),
]

urlpatterns += [
    path(
        "favicon.ico",
        serve,
        {
            "path": "favicon.ico",
            "document_root": os.path.join(BASE_DIR, "tasks/static"),
        },
    ),
]
if settings.LOAD_STATICS:
    urlpatterns += [re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT})]

urlpatterns = [
    path(r"issue-mgr/", include(urlpatterns)),
]

tasks/urls.py
from django.urls import path, re_path, include
from rest_framework.routers import DefaultRouter

from tasks import views

app_name = "tasks"

router = DefaultRouter()
router.register(r"tasks", views.TaskModelViewSet, basename="task")


urlpatterns = [
    path("", views.task_list_page, name="task_list_page"),
    re_path("", include(router.urls)),
    path("task/page/detail/<int:pk>", views.task_detail_page, name="task_detail"),
    path("task/page/create/", views.task_create_page, name="task_create_page"),
]

tasks/models.py
from django.conf import settings
from django.db import models

from tasks.enums import TaskStatusEnum


class Task(models.Model):
    title = models.CharField(max_length=256)
    status = models.CharField(
        choices=TaskStatusEnum.choices(),
        default=TaskStatusEnum.NOT_STARTED,
        max_length=2,
        help_text=TaskStatusEnum.help(),
    )
    description = models.TextField()

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def status_str(self):
        task_status = TaskStatusEnum.to_enum(self.status)
        return task_status.description if task_status else ""

    def owner_id(self):
        if self.owner:
            return self.owner.id
        return None

    def __str__(self):
        return f"Task(title={self.title})"

tasks/views.py
import logging

from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets
from rest_framework.authentication import BasicAuthentication

from issuetracker.utils.authentication import CsrfExemptSessionAuthentication
from issuetracker.utils.util_views import IsOwner
from tasks.enums import TaskStatusEnum
from tasks.models import Task
from tasks.serializers import TaskSerializer

logger = logging.getLogger(__name__)


@method_decorator(csrf_exempt, name="dispatch")
class TaskModelViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.order_by("-id").all()
    serializer_class = TaskSerializer
    permission_classes = [IsOwner]
    authentication_classes = (CsrfExemptSessionAuthentication, BasicAuthentication)

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)


def task_detail_page(request, pk):
    return render(request, "tasks/task_detail.html", {"pk": pk, "status_choices_dict": TaskStatusEnum.to_dict()})


def task_list_page(request):
    return render(request, "tasks/task_list.html")


def task_create_page(request):
    return render(request, "tasks/task_detail.html", {"status_choices_dict": TaskStatusEnum.to_dict()})

tasks/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

tasks/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>

      {% url 'tasks:task_list_page' as home %}

    <ul class="nav navbar-nav">
        <li class="{% if request.path == home %}active{% endif %}"><a href="{{ home }}">Tasks</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={{ home }}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={{ home }}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends "base_menu.html" %}
{% load static %}
{% block content %}

<form id="task_form">
    <div class="form-group">
        <label for="title">Title :</label>
        <input type="text" class="form-control" placeholder="Enter title" id="title">
    </div>

    <div class="form-group">
        <label for="status">Status :</label>

        <select class="form-control" id="status">
            {% for k, v in status_choices_dict.items %}
                <option value="{{k}}">{{v}}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="description">Description :</label>
        <textarea class="form-control" rows="5" id="description" placeholder="Enter Description" ></textarea>
    </div>

    <div class="col text-center">
    <input id="createButton" type="submit" class="btn btn-info btn-lg" value="Create" style="display: none;" />
    <input id="updateButton" type="submit" class="btn btn-info btn-lg" value="Update" style="display: none;" />
    </div>
</form>


<script>
{% if pk %}
    page_context = {
        "pk" : {{ pk }},
        "taskRetrieveApi" : "{% url 'tasks:task-detail' pk %}",
        "taskUpdateApi" : "{% url 'tasks:task-detail' pk %}",
        "taskListPage" : "{% url 'tasks:task_list_page' %}",
    }
{% else %}
    page_context = {
        "taskCreateApi" : "{% url 'tasks:task-list' %}",
        "taskListPage" : "{% url 'tasks:task_list_page' %}",
    }
//    page_context.taskUpdateApi = page_context.taskUpdateApi.substring(0, page_context.taskUpdateApi.length - 1);
{% endif %}
</script>
<script src="/issue-mgr/static/task_detail.js"></script>

{% endblock %}

tasks/templates/tasks/task_list.html
{% extends "base_menu.html" %}
{% load static %}
{% block head %}

<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.3.0/bootbox.js"></script>
{% endblock %}
{% block content %}

{% url 'tasks:task_create_page' as task_create_page %}

{% if user.is_authenticated %}
<div style="float:right">
<a href="{{task_create_page}}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-plus"></span> Create a new Task </a>
</div>
{% endif %}


<br clear="all"/>
<table id="tasklist" class="table table-striped table-bordered table-sm display" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Description</th>
        {% if user.is_authenticated %}
        <th>Edit</th>
        <th>Delete</th>
        {% endif %}
    </tr>
    </thead>
</table>

<script type="text/javascript">
var page_context = {
    taskListApi : "{% url 'tasks:task-list' %}",
    taskDeleteApi : "{% url 'tasks:task-detail' 0 %}",
    taskDetailPage : "{% url 'tasks:task_detail' 0 %}",
    taskListPage : "{% url 'tasks:task_list_page' %}",
    isUserAuthenticated : '{{ user.is_authenticated }}'==='True',
    userId : '{{user.id}}',
};
page_context.taskDetailPage = page_context.taskDetailPage.substring(0, page_context.taskDetailPage.length - 1);
page_context.taskDeleteApi = page_context.taskDeleteApi.substring(0, page_context.taskDeleteApi.length - 1);
</script>
<script src="/issue-mgr/static/task_list.js"></script>

{% endblock %}